# Cities dictionary
cities =
    {'Ciudad de México':
            {'Ecatepec':24,
            'Guadalajara':535,
            'Puebla':130,
            'Tijuana':2827,
            'Juárez':1805,
            'León':375,
            'Zapopan':541,
            'Monterrey':899,
            'Neza':16,
            'Hermosillo':1888,
            'Chihuahua':1440,
            'Naucalpan'12:,
            'Mérida':1306,
            'San Luis Potosí':402,
            'Aguascalientes':490,
            'Saltillo':836,
            'Mexicali':2640,
            'Culiacán':1215,
            'Acapulco':381}
        ,
    'Ecatepec':
            {'Ciudad de México':24,
            'Guadalajara':532,
            'Puebla':142,
            'Tijuana':2816,
            'Juárez':1794,
            'León':364,
            'Zapopan':538,
            'Monterrey':888,
            'Neza':27,
            'Hermosillo':1885,
            'Chihuahua':1429,
            'Naucalpan':32,
            'Mérida':1319,
            'San Luis Potosí':391,
            'Aguascalientes':479,
            'Saltillo':825,
            'Mexicali':2629,
            'Culiacán':1212,
            'Acapulco':404}
    ,
    'Guadalajara':
            {'Ciudad de México':535,
            'Ecatepec':532,
            'Puebla':668,
            'Tijuana':2229,
            'Juárez':1538,
            'León':224,
            'Zapopan':7,
            'Monterrey':795,
            'Neza':547,
            'Hermosillo':1361,
            'Chihuahua':1173,
            'Naucalpan':533,
            'Mérida':1844,
            'San Luis Potosí':331,
            'Aguascalientes':223,
            'Saltillo':705,
            'Mexicali':2058,
            'Culiacán':688,
            'Acapulco':866}
    ,
    'Puebla':
            {'Ciudad de México':130,
            'Ecatepec':142,
            'Guadalajara':668,
            'Tijuana':2957,
            'Juárez':1935,
            'León':505,
            'Zapopan':671,
            'Monterrey':1029,
            'Neza':123,
            'Hermosillo':2018,
            'Chihuahua':1570,
            'Naucalpan':143,
            'Mérida':1184,
            'San Luis Potosí':532,
            'Aguascalientes':620,
            'Saltillo':966,
            'Mexicali':2770,
            'Culiacán':1345,
            'Acapulco':426}
    ,
    'Tijuana':
            {'Ciudad de México':2827,
            'Ecatepec':2816,
            'Guadalajara':2229,
            'Puebla':2957,
            'Juárez':1183,
            'León':2463,
            'Zapopan':2223,
            'Monterrey':2195,
            'Neza':2840,
            'Hermosillo':873,
            'Chihuahua':1388,
            'Naucalpan':2824,
            'Mérida':4130,
            'San Luis Potosí':2406,
            'Aguascalientes':2334,
            'Saltillo':2114,
            'Mexicali':217,
            'Culiacán':1569,
            'Acapulco':3216}
    ,
    'Juárez':
            {'Ciudad de México':1805,
            'Ecatepec':1794,
            'Guadalajara':1538,
            'Puebla':1935,
            'Tijuana':1183,
            'León':1444,
            'Zapopan':1546,
            'Monterrey':1176,
            'Neza':1821,
            'Hermosillo':838,
            'Chihuahua':368,
            'Naucalpan':1805,
            'Mérida':3111,
            'San Luis Potosí':1387,
            'Aguascalientes':1314,
            'Saltillo':1094,
            'Mexicali':999,
            'Culiacán':1103,
            'Acapulco':2196}
    ,
    'León':
            {'Ciudad de México':375,
            'Ecatepec':1040,
            'Guadalajara':224,
            'Puebla':505,
            'Tijuana':2463,
            'Juárez':1444,
            'Zapopan':228,
            'Monterrey':692,
            'Neza':388,
            'Hermosillo':1575,
            'Chihuahua':1074,
            'Naucalpan':372,
            'Mérida':1678,
            'San Luis Potosí':179,
            'Aguascalientes':125,
            'Saltillo':607,
            'Mexicali':2274,
            'Culiacán':902,
            'Acapulco':763}
    ,
    'Zapopan':
            {'Ciudad de México':541,
            'Ecatepec':538,
            'Guadalajara':7,
            'Puebla':671,
            'Tijuana':2223,
            'Juárez':1546,
            'León':228,
            'Monterrey':,
            'Neza':,
            'Hermosillo':,
            'Chihuahua':,
            'Naucalpan':,
            'Mérida':,
            'San Luis Potosí':,
            'Aguascalientes':,
            'Saltillo':,
            'Mexicali':,
            'Culiacán':,
            'Acapulco':}
    ,
    'Monterrey':
            {'Ciudad de México':899,
            'Ecatepec':888,
            'Guadalajara':795,
            'Puebla':1029,
            'Tijuana':2195,
            'Juárez':1176,
            'León':692,
            'Zapopan':,
            'Neza':,
            'Hermosillo':,
            'Chihuahua':,
            'Naucalpan':,
            'Mérida':,
            'San Luis Potosí':,
            'Aguascalientes':,
            'Saltillo':,
            'Mexicali':,
            'Culiacán':,
            'Acapulco':}
    ,
    'Neza':
            {'Ciudad de México':16,
            'Ecatepec':27,
            'Guadalajara':547,
            'Puebla':123,
            'Tijuana':2840,
            'Juárez':1821,
            'León':388,
            'Zapopan':,
            'Monterrey':,
            'Hermosillo':,
            'Chihuahua':,
            'Naucalpan':,
            'Mérida':,
            'San Luis Potosí':,
            'Aguascalientes':,
            'Saltillo':,
            'Mexicali':,
            'Culiacán':,
            'Acapulco':}
    ,
    'Hermosillo':
            {'Ciudad de México':1888,
            'Ecatepec':1885,
            'Guadalajara':1361,
            'Puebla':2018,
            'Tijuana':873,
            'Juárez':838,
            'León':1575,
            'Zapopan':,
            'Monterrey':,
            'Neza':,
            'Chihuahua':,
            'Naucalpan':,
            'Mérida':,
            'San Luis Potosí':,
            'Aguascalientes':,
            'Saltillo':,
            'Mexicali':,
            'Culiacán':,
            'Acapulco':}
    ,
    'Chihuaha':
            {'Ciudad de México':1440,
            'Ecatepec':1429,
            'Guadalajara':1173,
            'Puebla':1570,
            'Tijuana':1388,
            'Juárez':368,
            'León':1074,
            'Zapopan':,
            'Monterrey':,
            'Neza':,
            'Hermosillo':,
            'Naucalpan':,
            'Mérida':,
            'San Luis Potosí':,
            'Aguascalientes':,
            'Saltillo':,
            'Mexicali':,
            'Culiacán':,
            'Acapulco':}
    ,
    'Naucalpan':
            {'Ciudad de México':12,
            'Ecatepec':32,
            'Guadalajara':533,
            'Puebla':143,
            'Tijuana':2824,
            'Juárez':1805,
            'León':372,
            'Zapopan':,
            'Monterrey':,
            'Neza':,
            'Hermosillo':,
            'Chihuahua':,
            'Mérida':,
            'San Luis Potosí':,
            'Aguascalientes':,
            'Saltillo':,
            'Mexicali':,
            'Culiacán':,
            'Acapulco':}
    ,
    'Mérida':
            {'Ciudad de México':1306,
            'Ecatepec':1319,
            'Guadalajara':1844,
            'Puebla':1184,
            'Tijuana':4130,
            'Juárez':3111,
            'León':1678,
            'Zapopan':,
            'Monterrey':,
            'Neza':,
            'Hermosillo':,
            'Chihuahua':,
            'Naucalpan':,
            'San Luis Potosí':,
            'Aguascalientes':,
            'Saltillo':,
            'Mexicali':,
            'Culiacán':,
            'Acapulco':}
    ,
    'San Luis Potosí':
            {'Ciudad de México':402,
            'Ecatepec':391,
            'Guadalajara':331,
            'Puebla':532,
            'Tijuana':2406,
            'Juárez':1387,
            'León':179,
            'Zapopan':,
            'Monterrey':,
            'Neza':,
            'Hermosillo':,
            'Chihuahua':,
            'Naucalpan':,
            'Mérida':,
            'Aguascalientes':,
            'Saltillo':,
            'Mexicali':,
            'Culiacán':,
            'Acapulco':}
    ,
    'Aguascalientes':
            {'Ciudad de México':490,
            'Ecatepec':479,
            'Guadalajara':223,
            'Puebla':620,
            'Tijuana':2334,
            'Juárez':1314,
            'León':125,
            'Zapopan':,
            'Monterrey':,
            'Neza':,
            'Hermosillo':,
            'Chihuahua':,
            'Naucalpan':,
            'Mérida':,
            'San Luis Potosí':,
            'Saltillo':,
            'Mexicali':,
            'Culiacán':,
            'Acapulco':}
    ,
    'Saltillo':
            {'Ciudad de México':836,
            'Ecatepec':825,
            'Guadalajara':705,
            'Puebla':966,
            'Tijuana':2114,
            'Juárez':1094,
            'León':607,
            'Zapopan':,
            'Monterrey':,
            'Neza':,
            'Hermosillo':,
            'Chihuahua':,
            'Naucalpan':,
            'Mérida':,
            'San Luis Potosí':,
            'Aguascalientes':,
            'Mexicali':,
            'Culiacán':,
            'Acapulco':}
    ,
    'Mexicali':
            {'Ciudad de México':2640,
            'Ecatepec':2629,
            'Guadalajara':2058,
            'Puebla':2770,
            'Tijuana':2114,
            'Juárez':999,
            'León':2274,
            'Zapopan':,
            'Monterrey':,
            'Neza':,
            'Hermosillo':,
            'Chihuahua':,
            'Naucalpan':,
            'Mérida':,
            'San Luis Potosí':,
            'Aguascalientes':,
            'Saltillo':,
            'Culiacán':,
            'Acapulco':}
    ,
    'Culiacán':
            {'Ciudad de México':1215,
            'Ecatepec':1212,
            'Guadalajara':688,
            'Puebla':1345,
            'Tijuana':217,
            'Juárez':1103,
            'León':902,
            'Zapopan':,
            'Monterrey':,
            'Neza':,
            'Hermosillo':,
            'Chihuahua':,
            'Naucalpan':,
            'Mérida':,
            'San Luis Potosí':,
            'Aguascalientes':,
            'Saltillo':,
            'Mexicali':,
            'Acapulco':}
    ,
    'Acapulco':
            {'Ciudad de México':381,
            'Ecatepec':404,
            'Guadalajara':866,
            'Puebla':426,
            'Tijuana':3216,
            'Juárez':2196,
            'León':763,
            'Zapopan':,
            'Monterrey':,
            'Neza':,
            'Hermosillo':,
            'Chihuahua':,
            'Naucalpan':,
            'Mérida':,
            'San Luis Potosí':,
            'Aguascalientes':,
            'Saltillo':,
            'Mexicali':,
            'Culiacán':}
    }
